### PR TITLE
UNIWISC Satellite FOSS

### PR DESCRIPTION
**Pull request by tiffanycmeyer13**
- To properly ingest the UNIWISC satellite data, needed the ar.com.hjg.pngj libraries

### CODE REVIEW

**Comment by srcarter3** [comment]
Did you copy these over from v18?  Or were they in the current nws repo somewhere?

**Comment by tiffanycmeyer13** [comment]
Just copied from version 18, they didn't exist in v20

**Comment by srcarter3** [comment]
Okay gotcha, do you think we should be worried about the version at all (I'm assuming it's an older version of the package)?

**Comment by tiffanycmeyer13** [comment]
Looks like we're on the latest release...hasn't been updated for a while: https://hjg.com.ar/pngj/releases/

**Pull request merged**
